Add loading spinner icon overlay when creating font
cod-ed/handwrite-web pull request #19
Opened 2021-08-30 20:41 UTC by sakshamarora1

2021-08-31 20:13 UTC, yashlamba commented on src/Home.js
> +  const [loading, setLoading] = useState(false);
We have 2 variables actually tracking the same thing in different ways, Let's remove this redundancy. A better idea would be to make a state variable:
0 -> Not doing anything
1 -> Image uploaded
2 -> Sending image
3 -> Generating font
4 -> Fetching font
5 -> Fetched
6 -> Error

And use them to display the status.

2021-08-31 20:14 UTC, yashlamba commented on src/Home.js
> +      {!loading ? (
This would be removed but still mentioning, the condition should be the opposite!?

2021-08-31 20:16 UTC, yashlamba requested changes
I was actually confused about how to display this loading but this looks super awesome and neat, I don't think we need an overlay, this looks super nice to me.

2021-09-01 10:19 UTC, sakshamarora1 commented on src/Home.js
> +      {!loading ? (
Yes it is for testing right now. Just for checking.

2021-09-02 16:15 UTC, yashlamba requested changes

2021-09-02 16:15 UTC, yashlamba commented on src/Home.js
>            fetch("http://handwritetest.herokuapp.com/handwrite/status/" + path).then((r) => r.json()).then((status) => {
We'll need to use async/await here. The requests are not running synchronously.

2021-09-02 16:15 UTC, yashlamba commented on src/Home.js
>        if (stat === 0) {
We can get rid of stat now and just use currentState

2021-09-04 10:40 UTC, yashlamba approved these changes

2021-09-04 10:40 UTC, merged